-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2022-07-26 16:02:18 CEST
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE SEQUENCE cust_emp_seq START WITH 100 INCREMENT BY 1 MAXVALUE 999 MINVALUE 100 CYCLE NOCACHE;

CREATE TABLE addresses (
    address_id NUMBER
        GENERATED ALWAYS AS IDENTITY ( START WITH 10 INCREMENT BY 10 NOCACHE ORDER )
    NOT NULL,
    st_name    VARCHAR2(40) NOT NULL,
    house_no   VARCHAR2(10) NOT NULL,
    apartment  VARCHAR2(10),
    postcode   CHAR(6) NOT NULL,
    city       VARCHAR2(30) NOT NULL
)
LOGGING;

ALTER TABLE addresses
    ADD CONSTRAINT addresses_postcode_ck CHECK ( substr(postcode, 3, 1) = '-'
                                                 AND to_number(replace(postcode, '-', '')) > 1
                                                 AND regexp_count(postcode, ' ') = 0 );

COMMENT ON COLUMN addresses.address_id IS
    'Primary Key of addresses table.';

COMMENT ON COLUMN addresses.st_name IS
    'Name of street. ';

COMMENT ON COLUMN addresses.house_no IS
    'House''s number.';

COMMENT ON COLUMN addresses.apartment IS
    'Optional apartment number.';

COMMENT ON COLUMN addresses.postcode IS
    'Postcode polish standard..Third char should be dash.';

COMMENT ON COLUMN addresses.city IS
    'Name of city.';

ALTER TABLE addresses ADD CONSTRAINT addresses_pk PRIMARY KEY ( address_id );

CREATE TABLE cartridges (
    cartridge_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1000 INCREMENT BY 10 MINVALUE 1000 NOCACHE ORDER )
    NOT NULL,
    title        VARCHAR2(100),
    price        NUMBER(5, 2) NOT NULL,
    color        VARCHAR2(30),
    availability CHAR(1 CHAR) DEFAULT 'Y' NOT NULL
)
LOGGING;

ALTER TABLE cartridges
    ADD CONSTRAINT cartridges_price_ck CHECK ( mod(price, 0.5) = 0 );

ALTER TABLE cartridges
    ADD CONSTRAINT cartridge_availability_ck CHECK ( availability IN ( 'N', 'R', 'Y' ) );

COMMENT ON COLUMN cartridges.cartridge_id IS
    'Primary Key of cartridges table.';

COMMENT ON COLUMN cartridges.title IS
    'Optional name of cartridge. E.g Sports, 5 in 1. ';

COMMENT ON COLUMN cartridges.price IS
    'Cost of the rental. Numbers divided by 5.';

COMMENT ON COLUMN cartridges.color IS
    'Optional color of the cartridge.';

COMMENT ON COLUMN cartridges.availability IS
    '(Y,N,R)';

ALTER TABLE cartridges ADD CONSTRAINT cartridges_pk PRIMARY KEY ( cartridge_id );

CREATE TABLE countries (
    country_id CHAR(3 CHAR) NOT NULL,
    name       VARCHAR2(100) NOT NULL
)
LOGGING;

COMMENT ON COLUMN countries.country_id IS
    'Primary Key of countries table as country unicode.';

COMMENT ON COLUMN countries.name IS
    'Name of Country.';

ALTER TABLE countries ADD CONSTRAINT countries_pk PRIMARY KEY ( country_id );

CREATE TABLE customers (
    customer_id NUMBER DEFAULT concat(to_number(to_char(sysdate, 'YYMMDD')), cust_emp_seq.NEXTVAL) NOT NULL,
    first_name  VARCHAR2(30) NOT NULL,
    last_name   VARCHAR2(30) NOT NULL,
    birth_date  DATE NOT NULL,
    patron_id   NUMBER,
    sex         CHAR(1 CHAR) NOT NULL,
    cre_date    DATE DEFAULT sysdate NOT NULL,
    address_id  NUMBER
        NOT NULL DEFERRABLE INITIALLY DEFERRED
)
LOGGING;

ALTER TABLE customers ADD CHECK ( length(customer_id) = 9 );

ALTER TABLE customers
    ADD CONSTRAINT customers_sex_ck CHECK ( sex IN ( 'F', 'M' ) );

COMMENT ON COLUMN customers.customer_id IS
    'Primary Key of customers table. Syssdate +  cust_emp sequence.';

COMMENT ON COLUMN customers.first_name IS
    'Customer''s first name.';

COMMENT ON COLUMN customers.last_name IS
    'Cutomer''s last name.';

COMMENT ON COLUMN customers.birth_date IS
    'Cutomer''s date of birth.';

COMMENT ON COLUMN customers.sex IS
    'Sex (M,F).';

COMMENT ON COLUMN customers.cre_date IS
    'Creation date of customer''s account. Sysdate.';

COMMENT ON COLUMN customers.address_id IS
    'Address ID for thecustomers.  Foreign key to address_id column in the addresses table.';

ALTER TABLE customers ADD CONSTRAINT customers_pk PRIMARY KEY ( customer_id );

CREATE TABLE detained_cartridges (
    rental_id    NUMBER NOT NULL,
    customer_id  NUMBER NOT NULL,
    cartridge_id NUMBER NOT NULL,
    out_date     DATE NOT NULL,
    in_date      DATE DEFAULT sysdate NOT NULL,
    price_paid   NUMBER NOT NULL
)
LOGGING;

COMMENT ON COLUMN detained_cartridges.rental_id IS
    'Foreign key to rental_id column in therentals table.';

COMMENT ON COLUMN detained_cartridges.customer_id IS
    'Customer ID for the rented cartridge.';

COMMENT ON COLUMN detained_cartridges.cartridge_id IS
    'Rented cartridge ID.';

COMMENT ON COLUMN detained_cartridges.out_date IS
    'Darte of rent. ';

COMMENT ON COLUMN detained_cartridges.in_date IS
    'Date of back.';

COMMENT ON COLUMN detained_cartridges.price_paid IS
    'Paid amount';

ALTER TABLE detained_cartridges ADD CONSTRAINT detained_cartridges_rental_id_un UNIQUE ( rental_id );

CREATE TABLE developers (
    developer_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 100 INCREMENT BY 100 MINVALUE 100 NOCACHE ORDER )
    NOT NULL,
    name         VARCHAR2(100) NOT NULL,
    estb_date    DATE,
    country_id   CHAR(3 CHAR)
)
LOGGING;

COMMENT ON COLUMN developers.developer_id IS
    'Primary Key of developers table.';

COMMENT ON COLUMN developers.name IS
    'Name of company.';

COMMENT ON COLUMN developers.estb_date IS
    'Release date.';

COMMENT ON COLUMN developers.country_id IS
    'Country ID for the developers. Foreign key to country_id column in the countries table.';

ALTER TABLE developers ADD CONSTRAINT developers_pk PRIMARY KEY ( developer_id );

CREATE TABLE employees (
    employee_id NUMBER DEFAULT concat(to_number(to_char(sysdate, 'YYMMDD')), cust_emp_seq.NEXTVAL)
        NOT NULL DEFERRABLE INITIALLY DEFERRED,
    first_name  VARCHAR2(30) NOT NULL,
    last_name   VARCHAR2(30) NOT NULL,
    birth_date  DATE NOT NULL,
    hire_date   DATE DEFAULT sysdate NOT NULL,
    sex         CHAR(1 CHAR) NOT NULL,
    address_id  NUMBER
        NOT NULL DEFERRABLE INITIALLY DEFERRED,
    db_user     VARCHAR2(30)
)
LOGGING;

ALTER TABLE employees
    ADD CONSTRAINT ck_employees_sex CHECK ( sex IN ( 'F', 'M' ) );

COMMENT ON COLUMN employees.employee_id IS
    'Primary Key of empolyees table. Syssdate +  cust_emp sequence. ';

COMMENT ON COLUMN employees.first_name IS
    'Employee''s first name.';

COMMENT ON COLUMN employees.last_name IS
    'Employee''s last name.';

COMMENT ON COLUMN employees.birth_date IS
    'Employee''s date of birth';

COMMENT ON COLUMN employees.hire_date IS
    'Hire date of employee.';

COMMENT ON COLUMN employees.sex IS
    'Sex (M,F).';

COMMENT ON COLUMN employees.address_id IS
    'Assress  ID for the employees. Foreign key to address_id column in the addresses table.';

ALTER TABLE employees ADD CONSTRAINT employees_pk PRIMARY KEY ( employee_id );

CREATE TABLE games (
    game_id      NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    title        VARCHAR2(50) NOT NULL,
    grelease     DATE,
    gmode        VARCHAR2(30) DEFAULT 'single-player',
    developer_id NUMBER,
    genre_id     NUMBER
)
LOGGING;

ALTER TABLE games
    ADD CONSTRAINT ck_games_mode CHECK ( gmode IN ( 'gun', 'multiplayers', 'single-player' ) );

COMMENT ON COLUMN games.game_id IS
    'Primary Key of games table.';

COMMENT ON COLUMN games.title IS
    'Name of the game.';

COMMENT ON COLUMN games.grelease IS
    'Date of published.';

COMMENT ON COLUMN games.gmode IS
    'Mode of the game. (single-player, multiplayers, gun).';

COMMENT ON COLUMN games.developer_id IS
    'Developer ID for the game.  Foreign key to developer_id column in the developers table.';

COMMENT ON COLUMN games.genre_id IS
    'Genere ID for the game.  Foreign key to genre_id column in the genres table.';

ALTER TABLE games ADD CONSTRAINT games_pk PRIMARY KEY ( game_id );

CREATE TABLE games_cartridges (
    game_id      NUMBER NOT NULL,
    cartridge_id NUMBER NOT NULL
)
LOGGING;

COMMENT ON COLUMN games_cartridges.game_id IS
    'Multiple Primary Key with column cartridge_id of games_cartridges table.';

COMMENT ON COLUMN games_cartridges.cartridge_id IS
    'Multiple Primary Key with column game_id of games_cartridges  table.';

ALTER TABLE games_cartridges ADD CONSTRAINT games_cartriges_pk PRIMARY KEY ( game_id,
                                                                             cartridge_id );

CREATE TABLE genres (
    genre_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 100 INCREMENT BY 100 MINVALUE 100 NOCACHE ORDER )
    NOT NULL,
    name     VARCHAR2(50) NOT NULL
)
LOGGING;

COMMENT ON COLUMN genres.genre_id IS
    'Primary Key of genres table.';

COMMENT ON COLUMN genres.name IS
    'Genre''s name.';

ALTER TABLE genres ADD CONSTRAINT genres_pk PRIMARY KEY ( genre_id );

CREATE TABLE rentals (
    rental_id    NUMBER
        GENERATED ALWAYS AS IDENTITY ( START WITH 1 CACHE 20 ORDER )
    NOT NULL,
    employee_id  NUMBER NOT NULL,
    customer_id  NUMBER NOT NULL,
    cartridge_id NUMBER NOT NULL,
    out_date     DATE DEFAULT sysdate NOT NULL,
    in_date      DATE
)
LOGGING;

COMMENT ON COLUMN rentals.rental_id IS
    'Primary Key of  rentals table.';

COMMENT ON COLUMN rentals.employee_id IS
    'ID of employee who made a transaction.  Foreign key to employee_id column in the employees table.';

COMMENT ON COLUMN rentals.customer_id IS
    'ID of custome.  Foreign key to customer_id column in the customers table.';

COMMENT ON COLUMN rentals.cartridge_id IS
    ' Foreign Key to cartridge_id column in the cartridges table.';

COMMENT ON COLUMN rentals.out_date IS
    'Darte of rent. sysdate.';

COMMENT ON COLUMN rentals.in_date IS
    'Date of back.';

ALTER TABLE rentals ADD CONSTRAINT rentals_pk PRIMARY KEY ( rental_id );

CREATE TABLE reservations (
    reservation_id NUMBER
        GENERATED ALWAYS AS IDENTITY ( START WITH 1 MINVALUE 1 CACHE 10 ORDER )
    NOT NULL,
    res_date       DATE DEFAULT sysdate NOT NULL,
    customer_id    NUMBER NOT NULL,
    cartridge_id   NUMBER NOT NULL
)
LOGGING;

COMMENT ON COLUMN reservations.reservation_id IS
    'Primary Key of reservations table.';

COMMENT ON COLUMN reservations.res_date IS
    'Reservation date. Only for the same day of rental.';

COMMENT ON COLUMN reservations.customer_id IS
    'Customer ID for the reservation.  Foreign key to customer_id column in the customers table.';

COMMENT ON COLUMN reservations.cartridge_id IS
    'Cartridge ID for the reservation..  Foreign key to cartridge_id column in the cartridges table.';

ALTER TABLE reservations ADD CONSTRAINT reservations_pk PRIMARY KEY ( reservation_id );

ALTER TABLE reservations ADD CONSTRAINT reservations_cartridge_id_un UNIQUE ( cartridge_id );

CREATE TABLE unreleased_res (
    reservation_id NUMBER NOT NULL,
    res_date       DATE DEFAULT sysdate NOT NULL,
    customer_id    NUMBER NOT NULL,
    cartridge_id   NUMBER NOT NULL
)
LOGGING;

COMMENT ON COLUMN unreleased_res.reservation_id IS
    'Primary Key of reservations table.';

COMMENT ON COLUMN unreleased_res.res_date IS
    'Reservation date. Only for the same day of rental.';

COMMENT ON COLUMN unreleased_res.customer_id IS
    'Customer ID for the reservation.  Foreign key to customer_id column in the customers table.';

COMMENT ON COLUMN unreleased_res.cartridge_id IS
    'Cartridge ID for the reservation..  Foreign key to cartridge_id column in the cartridges table.';

ALTER TABLE unreleased_res ADD CONSTRAINT unreleased_res_reservation_id_un UNIQUE ( reservation_id );

ALTER TABLE customers
    ADD CONSTRAINT customers_addresses_fk FOREIGN KEY ( address_id )
        REFERENCES addresses ( address_id )
    NOT DEFERRABLE;

ALTER TABLE customers
    ADD CONSTRAINT customers_customers_fk FOREIGN KEY ( patron_id )
        REFERENCES customers ( customer_id )
    NOT DEFERRABLE;

ALTER TABLE detained_cartridges
    ADD CONSTRAINT detained_cartridges_rentals_fk FOREIGN KEY ( rental_id )
        REFERENCES rentals ( rental_id )
    NOT DEFERRABLE;

ALTER TABLE developers
    ADD CONSTRAINT developers_countries_fk FOREIGN KEY ( country_id )
        REFERENCES countries ( country_id )
    NOT DEFERRABLE;

ALTER TABLE employees
    ADD CONSTRAINT employees_addresses_fk FOREIGN KEY ( address_id )
        REFERENCES addresses ( address_id )
    NOT DEFERRABLE;

ALTER TABLE games_cartridges
    ADD CONSTRAINT games_cartriges_cartriges_fk FOREIGN KEY ( cartridge_id )
        REFERENCES cartridges ( cartridge_id )
    NOT DEFERRABLE;

ALTER TABLE games_cartridges
    ADD CONSTRAINT games_cartriges_games_fk FOREIGN KEY ( game_id )
        REFERENCES games ( game_id )
    NOT DEFERRABLE;

ALTER TABLE games
    ADD CONSTRAINT games_developers_fk FOREIGN KEY ( developer_id )
        REFERENCES developers ( developer_id )
    NOT DEFERRABLE;

ALTER TABLE games
    ADD CONSTRAINT games_genres_fk FOREIGN KEY ( genre_id )
        REFERENCES genres ( genre_id )
    NOT DEFERRABLE;

ALTER TABLE rentals
    ADD CONSTRAINT rentals_cartridges_fk FOREIGN KEY ( cartridge_id )
        REFERENCES cartridges ( cartridge_id )
    NOT DEFERRABLE;

ALTER TABLE rentals
    ADD CONSTRAINT rentals_customers_fk FOREIGN KEY ( customer_id )
        REFERENCES customers ( customer_id )
    NOT DEFERRABLE;

ALTER TABLE rentals
    ADD CONSTRAINT rentals_employees_fk FOREIGN KEY ( employee_id )
        REFERENCES employees ( employee_id )
    NOT DEFERRABLE;

ALTER TABLE reservations
    ADD CONSTRAINT reservations_cartridges_fk FOREIGN KEY ( cartridge_id )
        REFERENCES cartridges ( cartridge_id )
    NOT DEFERRABLE;

ALTER TABLE reservations
    ADD CONSTRAINT reservations_customers_fk FOREIGN KEY ( customer_id )
        REFERENCES customers ( customer_id )
    NOT DEFERRABLE;

ALTER TABLE unreleased_res
    ADD CONSTRAINT unreleased_res_reservations_fk FOREIGN KEY ( reservation_id )
        REFERENCES reservations ( reservation_id )
    NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             0
-- ALTER TABLE                             36
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0